{
  "formatVersion": "1.1",
  "component": {
    "group": "net.snakefangox",
    "module": "rapid-register",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "rapid-register-1.1.0.jar",
          "url": "rapid-register-1.1.0.jar",
          "size": 43288,
          "sha512": "2242c8c361b984c69af42c64abf40de4aabccf7db792a0e58ed08d2aa4830cbd5a6b25eb990675edfd5358f056ca82464c322da3f0be19f87233010fb13d2aef",
          "sha256": "693859b3d4d6e339aa05f922cc4213af586eb8861bb40c6cdbbf9680dd4983fc",
          "sha1": "2dadf5fe5ead000fc4cf22dba9f025333398f413",
          "md5": "1cb9230d96b4d21abc9b0ca81cdb9608"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.91.3+1.20.4"
          }
        }
      ],
      "files": [
        {
          "name": "rapid-register-1.1.0.jar",
          "url": "rapid-register-1.1.0.jar",
          "size": 43288,
          "sha512": "2242c8c361b984c69af42c64abf40de4aabccf7db792a0e58ed08d2aa4830cbd5a6b25eb990675edfd5358f056ca82464c322da3f0be19f87233010fb13d2aef",
          "sha256": "693859b3d4d6e339aa05f922cc4213af586eb8861bb40c6cdbbf9680dd4983fc",
          "sha1": "2dadf5fe5ead000fc4cf22dba9f025333398f413",
          "md5": "1cb9230d96b4d21abc9b0ca81cdb9608"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rapid-register-1.1.0-sources.jar",
          "url": "rapid-register-1.1.0-sources.jar",
          "size": 25530,
          "sha512": "1bf80aef215c30f1ea440fa72112f1532c097e704860e3277bfeeaa3f1fc8f38fe3f82592dc6bde41eaf028a66ff750831e3d66d827f7fbf86d8a9096629c5a7",
          "sha256": "ff730e4b877fb95c71b5cc8483552a97a7cd123738492a8d6a1bce5c173b6283",
          "sha1": "09d8c04a636448d893beec2f4604f80a87f79e9e",
          "md5": "ecb914033aa907a1f365b2d3ab9e223f"
        }
      ]
    }
  ]
}
