{
  "formatVersion": "1.1",
  "component": {
    "group": "net.snakefangox",
    "module": "rapid-register",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "rapid-register-1.0.0.jar",
          "url": "rapid-register-1.0.0.jar",
          "size": 43255,
          "sha512": "e127e3047e843fa3a578ffaa6cb1d8dfb6d3a11abb2e454624189d5616a54e8034251330ca04ce5b0c35cf7c00613612c69ff3793391af21a9cb9eefa2e21159",
          "sha256": "1ba230c1079fce1e798df05a6265827dfdcadbd80477327cf90fea495ec32406",
          "sha1": "9f17535964cdea9c126f34c3eef6f0d0848a307e",
          "md5": "a90216f075becd3eabad434a1bb8d7f6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.91.3+1.20.4"
          }
        }
      ],
      "files": [
        {
          "name": "rapid-register-1.0.0.jar",
          "url": "rapid-register-1.0.0.jar",
          "size": 43255,
          "sha512": "e127e3047e843fa3a578ffaa6cb1d8dfb6d3a11abb2e454624189d5616a54e8034251330ca04ce5b0c35cf7c00613612c69ff3793391af21a9cb9eefa2e21159",
          "sha256": "1ba230c1079fce1e798df05a6265827dfdcadbd80477327cf90fea495ec32406",
          "sha1": "9f17535964cdea9c126f34c3eef6f0d0848a307e",
          "md5": "a90216f075becd3eabad434a1bb8d7f6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rapid-register-1.0.0-sources.jar",
          "url": "rapid-register-1.0.0-sources.jar",
          "size": 25513,
          "sha512": "11d5fbc24b65d4630d90bd6a7969db525ca985d41812dd91a9af84ab6b1b132d1494b8721757ff723cc5decbdf420ec7e0df294ad608b357e4a87616d5d8638b",
          "sha256": "43bd080d8edefa60ea1852354aa519fe3ab671633712df0b09b617e6f4fb868f",
          "sha1": "7d81b372862cdc35d9ff1fcfe4fb4efa573f2a77",
          "md5": "fe9d234a1487e3d615a348f788d55534"
        }
      ]
    }
  ]
}
