{
  "formatVersion": "1.1",
  "component": {
    "group": "net.snakefangox",
    "module": "rapid-register",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "rapid-register-1.0.0.jar",
          "url": "rapid-register-1.0.0.jar",
          "size": 43288,
          "sha512": "e4307b86bcf03b37052ea083ba01db24423093e2f41b9080ab7b2ae706f489a5c4608193b91f838e405f6631fdaca90a3925190fe163748bd4e596cd53405bfe",
          "sha256": "d06ba3f68599484431bb3a37ed3d712f1c69890df47f0f07b630662da451f266",
          "sha1": "329d3d962d156ff43844f3e92f90b2131d9632a8",
          "md5": "6049ec71f52208c12fd5f7895de4bc46"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.91.3+1.20.4"
          }
        }
      ],
      "files": [
        {
          "name": "rapid-register-1.0.0.jar",
          "url": "rapid-register-1.0.0.jar",
          "size": 43288,
          "sha512": "e4307b86bcf03b37052ea083ba01db24423093e2f41b9080ab7b2ae706f489a5c4608193b91f838e405f6631fdaca90a3925190fe163748bd4e596cd53405bfe",
          "sha256": "d06ba3f68599484431bb3a37ed3d712f1c69890df47f0f07b630662da451f266",
          "sha1": "329d3d962d156ff43844f3e92f90b2131d9632a8",
          "md5": "6049ec71f52208c12fd5f7895de4bc46"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rapid-register-1.0.0-sources.jar",
          "url": "rapid-register-1.0.0-sources.jar",
          "size": 25530,
          "sha512": "a71482d154a0e4066891092f470adf89723505831c27e412ef9db7f33cff2024b2784b616714cde7a523b05ec9b080762b5de0b118642045f73e314f4d51b8e2",
          "sha256": "0da81fecf5f9e122a63f5faeb7a8cc1c718ddd1a104d5a433f59bb96e4c9333f",
          "sha1": "089ce336ebfdb3870e727472ce9592abcb8c2fe2",
          "md5": "045ad249909863180a9ce00fcf9106a5"
        }
      ]
    }
  ]
}
